import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { Color } from "jspdf-autotable";

export interface ReportData {
    patientName: string;
    condition: string;
    riskLevel: string;
    probability: number;
    diagnosis: string;
    clinicalData: { label: string; value: string; unit?: string }[];
    advice: string[];
}

const BRAND_COLORS: Record<string, [number, number, number]> = {
    primary: [108, 99, 255], // hsl(244, 98%, 69%)
    success: [34, 197, 94],  // hsl(142, 72%, 42%)
    warning: [245, 158, 11], // hsl(38, 92%, 55%)
    destructive: [239, 68, 68] // hsl(0, 72%, 55%)
};

const getRiskColor = (level: string): [number, number, number] => {
    const l = level.toLowerCase();
    if (l.includes("low") || l.includes("normal") || l.includes("success")) return BRAND_COLORS.success;
    if (l.includes("moderate") || l.includes("borderline") || l.includes("benign") || l.includes("warning")) return BRAND_COLORS.warning;
    if (l.includes("high") || l.includes("malignant") || l.includes("destructive")) return BRAND_COLORS.destructive;
    return [100, 100, 100];
};

export const generatePDFReport = (data: ReportData) => {
    const doc = new jsPDF();
    const timestamp = new Date().toLocaleString();
    const riskColor = getRiskColor(data.riskLevel);

    // Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.setTextColor(219, 39, 119); // Pink accent
    doc.text("SheHealth-AI", 14, 22);

    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text("Clinical Screening Assessment", 14, 30);

    // Patient Info Box
    doc.setDrawColor(230, 230, 230);
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(14, 38, 182, 25, 3, 3, "FD");

    doc.setFontSize(10);
    doc.setTextColor(80, 80, 80);
    doc.text("PATIENT NAME:", 20, 48);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 0, 0);
    doc.text(data.patientName.toUpperCase() || "NOT PROVIDED", 55, 48);

    doc.setFont("helvetica", "normal");
    doc.setTextColor(80, 80, 80);
    doc.text("REPORT DATE:", 20, 56);
    doc.text(timestamp, 55, 56);
    doc.text("CONDITION:", 120, 56);
    doc.text(data.condition.toUpperCase(), 150, 56);

    // Result Summary Section
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 0, 0);
    doc.text("AI Assessment Result", 14, 78);

    autoTable(doc, {
        startY: 83,
        head: [["Assessment Metric", "Value"]],
        body: [
            ["Risk Classification", data.riskLevel.toUpperCase()],
            ["Statistical Probability", `${data.probability}%`],
            ["Clinical Summary", data.diagnosis]
        ],
        headStyles: { fillColor: BRAND_COLORS.primary as Color, fontStyle: "bold" },
        columnStyles: {
            0: { cellWidth: 50, fontStyle: "bold" },
            1: { cellWidth: "auto" }
        },
        didParseCell: (cellData) => {
            if (cellData.section === "body" && cellData.column.index === 1 && cellData.row.index === 0) {
                cellData.cell.styles.textColor = riskColor as Color;
                cellData.cell.styles.fontStyle = "bold";
            }
        }
    });

    // Clinical Parameters Section
    const nextY = (doc as any).lastAutoTable.finalY + 15;
    doc.setFontSize(14);
    doc.text("Clinical Parameters Provided", 14, nextY);

    autoTable(doc, {
        startY: nextY + 5,
        head: [["Parameter", "Observed Value", "Unit"]],
        body: data.clinicalData.map(d => [d.label, d.value, d.unit || "—"]),
        headStyles: { fillColor: [100, 116, 139] as Color },
    });

    // Advice Section
    const adviceY = (doc as any).lastAutoTable.finalY + 15;
    doc.setFontSize(14);
    doc.text("Recommendations & Next Steps", 14, adviceY);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    let currentY = adviceY + 8;
    data.advice.forEach((item, index) => {
        const text = `${index + 1}. ${item}`;
        const splitText = doc.splitTextToSize(text, 180);
        if (currentY + (splitText.length * 5) > 270) {
            doc.addPage();
            currentY = 20;
        }
        doc.text(splitText, 14, currentY);
        currentY += (splitText.length * 5) + 2;
    });

    // Footer / Disclaimer
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        const pageHeight = doc.internal.pageSize.height;
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        const disclaimer = "Medical Disclaimer: This report is generated by an AI screening tool for educational purposes. It is NOT a medical diagnosis. Always consult a qualified healthcare professional.";
        const splitDisclaimer = doc.splitTextToSize(disclaimer, 180);
        doc.text(splitDisclaimer, 14, pageHeight - 15);
        doc.text(`Page ${i} of ${pageCount}`, 180, pageHeight - 10);
    }

    doc.save(`${data.patientName || "SheHealth"}_${data.condition.replace(/\s+/g, '_')}_Report.pdf`);
};
